logging.level:
  ru.practicum.shareit: DEBUG
  org.springframework.jdbc: DEBUG
#  org.hibernate.SQL: DEBUG
#  org.hibernate.type: TRACE
#  org.hibernate.orm.jdbc.bind: TRACE

spring:
  sql:
    init:
      mode: always
      encoding: UTF-8
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/Dbshareit
    username: postgres
    password: postgres

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          time_zone: UTC+5
    database-platform: org.hibernate.dialect.PostgreSQLDialect

