logging.level:
  ru.practicum.shareit: DEBUG
  org.springframework.jdbc: DEBUG



spring:
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:file:./db/shareit
    driverClassName: org.h2.Driver
    username: sa
    password: password

#  org.springframework.orm.jpa: INFO
#  org.springframework.transaction: INFO
#  org.springframework.transaction.interceptor: TRACE
#  org.springframework.orm.jpa.JpaTransactionManager: DEBUG



#    jpa:
#      hibernate:
#        ddl-auto: none
#      properties:
#        hibernate:
#          format_sql: true

