logging.level:
  ru.practicum.shareit: DEBUG
  org.springframework.jdbc: DEBUG


server:
  port: 9090

spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
  sql:
    init:
      mode: always
  

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/Dbshareit
    username: postgres
    password: postgres

